# Generated by Django 2.2.5 on 2021-08-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_like', models.IntegerField(default=0)),
                ('m_title', models.CharField(max_length=100)),
                ('artist_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='MyPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_like', models.IntegerField(default=0)),
                ('made_by', models.CharField(default='신지환', max_length=20)),
                ('myplaylist_name', models.CharField(max_length=20)),
                ('music_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Music')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_contents', models.TextField()),
                ('myplaylist_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myplaylist_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist')),
            ],
        ),
    ]
