# Generated by Django 2.2.5 on 2021-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
