# Generated by Django 2.2.5 on 2021-08-04 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myplaylist',
            name='mp_title',
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='mp_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='music_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='myplaylist_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistcomment',
            name='myplaylist_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist'),
        ),
    ]
