# Generated by Django 2.2.5 on 2021-08-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='m_videoCd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
