# Generated by Django 2.2.24 on 2021-08-02 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist_fk',
        ),
        migrations.RemoveField(
            model_name='myplaylist',
            name='music_fk',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='p_like',
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='mp_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='mp_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='music_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistcomment',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
