# Generated by Django 2.2.5 on 2021-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplaylist',
            name='myplaylist_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
