# Generated by Django 2.2.5 on 2021-08-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210812_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='list_pub_date',
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='list_pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
