# Generated by Django 2.2.5 on 2021-08-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_myplaylist_myplaylist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='p_like',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_name',
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='p_like',
            field=models.IntegerField(default=0),
        ),
    ]
