# Generated by Django 2.2.5 on 2021-08-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_myplaylist_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplaylist',
            name='made_by',
            field=models.CharField(default='신지환', max_length=20),
        ),
    ]
