# Generated by Django 2.2.5 on 2021-08-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_remove_myplaylist_music_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myplaylist',
            old_name='mp_title',
            new_name='myplaylist_name',
        ),
        migrations.RenameField(
            model_name='myplaylist',
            old_name='mp_like',
            new_name='p_like',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user_fk',
        ),
        migrations.RemoveField(
            model_name='playlistcomment',
            name='user_fk',
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='music_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
            preserve_default=False,
        ),
    ]
