# Generated by Django 2.2.5 on 2021-08-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_myplaylist_music_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplaylist',
            name='music_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
            preserve_default=False,
        ),
    ]
