# Generated by Django 2.2.5 on 2021-08-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_myplaylist_music_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myplaylist',
            name='music_fk',
        ),
    ]
