# Generated by Django 2.2.5 on 2021-08-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_myplaylist_music_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplaylist',
            name='music_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='myplaylist_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist'),
        ),
        migrations.AlterField(
            model_name='playlistcomment',
            name='myplaylist_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist'),
        ),
    ]
