# Generated by Django 2.2.5 on 2021-08-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210803_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplaylist',
            name='list_pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
