# Generated by Django 2.2.24 on 2021-08-04 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0014_myplaylist_list_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myplaylist',
            old_name='p_like',
            new_name='mp_like',
        ),
        migrations.RemoveField(
            model_name='myplaylist',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='myplaylist',
            name='music_fk',
        ),
        migrations.RemoveField(
            model_name='myplaylist',
            name='myplaylist_name',
        ),
        migrations.AddField(
            model_name='myplaylist',
            name='mp_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='music_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistcomment',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
