# Generated by Django 2.2.24 on 2021-08-04 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20210804_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music_fk',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='myplaylist_fk',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user_fk',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
