# Generated by Django 2.2.24 on 2021-08-04 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0016_auto_20210804_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplaylist',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='music_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='myplaylist_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MyPlaylist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
